-- MySQL Script generated by MySQL Workbench
-- Mon Jun  2 23:47:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd-turnat-spring
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd-turnat-spring
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-turnat-spring` DEFAULT CHARACTER SET utf8 ;
USE `bd-turnat-spring` ;

-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `localidad` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `altura` INT NOT NULL,
  `depto` VARCHAR(45) NULL,
  PRIMARY KEY (`idDireccion`),
  UNIQUE INDEX `idDireccion_UNIQUE` (`idDireccion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `fk_Persona_Direccion1_idx` (`Direccion_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `bd-turnat-spring`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Cliente` (
  `Cliente_idPersona` INT NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  INDEX `fk_table1_Cliente_idx` (`Cliente_idPersona` ASC) VISIBLE,
  PRIMARY KEY (`Cliente_idPersona`),
  CONSTRAINT `fk_table1_Cliente`
    FOREIGN KEY (`Cliente_idPersona`)
    REFERENCES `bd-turnat-spring`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Disponible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Disponible` (
  `idDisponibilidad` INT NOT NULL AUTO_INCREMENT,
  `horafin` TIME NOT NULL,
  `horainicio` TIME NOT NULL,
  `lunes` TINYINT NOT NULL,
  `martes` TINYINT NOT NULL,
  `miercoles` TINYINT NOT NULL,
  `jueves` TINYINT NOT NULL,
  `viernes` TINYINT NOT NULL,
  `sabado` TINYINT NOT NULL,
  `domingo` TINYINT NOT NULL,
  PRIMARY KEY (`idDisponibilidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `duracion` TIME NOT NULL,
  `Disponible_idDisponibilidad` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `Disponible_idDisponibilidad`),
  INDEX `fk_Servicio_Disponible1_idx` (`Disponible_idDisponibilidad` ASC) VISIBLE,
  UNIQUE INDEX `idServicio_UNIQUE` (`idServicio` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_Disponible1`
    FOREIGN KEY (`Disponible_idDisponibilidad`)
    REFERENCES `bd-turnat-spring`.`Disponible` (`idDisponibilidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Empleado` (
  `Persona_idPersona` INT NOT NULL,
  `legajo` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  INDEX `fk_Empleado_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  PRIMARY KEY (`Persona_idPersona`),
  INDEX `fk_Empleado_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `bd-turnat-spring`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `bd-turnat-spring`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `Direccion_idDireccion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_Sucursal_Direccion1_idx` (`Direccion_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_Sucursal_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `bd-turnat-spring`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Servicio_has_Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Servicio_has_Sucursal` (
  `Servicio_idServicio` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`Servicio_idServicio`, `Sucursal_idSucursal`),
  INDEX `fk_Servicio_has_Sucursal_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
  INDEX `fk_Servicio_has_Sucursal_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_has_Sucursal_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `bd-turnat-spring`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicio_has_Sucursal_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `bd-turnat-spring`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`FechaYHora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`FechaYHora` (
  `idFechaYHora` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`idFechaYHora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnat-spring`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-turnat-spring`.`Turno` (
  `idTurno` INT NOT NULL AUTO_INCREMENT,
  `Cliente_Cliente_idPersona` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `FechaYHora_idFechaYHora` INT NOT NULL,
  PRIMARY KEY (`idTurno`),
  INDEX `fk_Turno_Cliente1_idx` (`Cliente_Cliente_idPersona` ASC) VISIBLE,
  INDEX `fk_Turno_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  INDEX `fk_Turno_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  INDEX `fk_Turno_FechaYHora1_idx` (`FechaYHora_idFechaYHora` ASC) VISIBLE,
  CONSTRAINT `fk_Turno_Cliente1`
    FOREIGN KEY (`Cliente_Cliente_idPersona`)
    REFERENCES `bd-turnat-spring`.`Cliente` (`Cliente_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `bd-turnat-spring`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `bd-turnat-spring`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_FechaYHora1`
    FOREIGN KEY (`FechaYHora_idFechaYHora`)
    REFERENCES `bd-turnat-spring`.`FechaYHora` (`idFechaYHora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
