-- MySQL Script generated by MySQL Workbench
-- Sun May  4 19:20:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd-turnos-grupo01
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd-turnos-grupo01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-turnos-grupo01` DEFAULT CHARACTER SET utf8 ;
USE `bd-turnos-grupo01` ;



-- -----------------------------------------------------
-- Table `bd-turnos-grupo01`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-turnos-grupo01`.`Persona` ;

CREATE TABLE IF NOT EXISTS `bd-turnos-grupo01`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnos-grupo01`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-turnos-grupo01`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `bd-turnos-grupo01`.`Cliente` (
  `email` VARCHAR(80) NOT NULL,
  `telefono` INT NOT NULL,
  `idPersona` INT NOT NULL,
  INDEX `fk_cliente_Persona_idx` (`idPersona` ASC) VISIBLE,
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `fk_cliente_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `bd-turnos-grupo01`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnos-grupo01`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-turnos-grupo01`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `bd-turnos-grupo01`.`Empleado` (
  `legajo` INT NOT NULL ,
  `cargo` VARCHAR(90) NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_empleado_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `bd-turnos-grupo01`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnos-grupo01`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-turnos-grupo01`.`Servicio` ;

CREATE TABLE IF NOT EXISTS `bd-turnos-grupo01`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnos-grupo01`.`Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-turnos-grupo01`.`Sucursal` ;

CREATE TABLE IF NOT EXISTS `bd-turnos-grupo01`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(80) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnos-grupo01`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-turnos-grupo01`.`Estado` ;

CREATE TABLE IF NOT EXISTS `bd-turnos-grupo01`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd-turnos-grupo01`.`Turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-turnos-grupo01`.`Turno` ;

CREATE TABLE IF NOT EXISTS `bd-turnos-grupo01`.`Turno` (
  `idTurno` INT NOT NULL AUTO_INCREMENT,
  `fechaYHora` DATETIME NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  `Cliente_idPersona` INT NULL,
  `Empleado_idPersona` INT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idTurno`),
  INDEX `fk_Turno_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  INDEX `fk_Turno_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
  INDEX `fk_Turno_Cliente1_idx` (`Cliente_idPersona` ASC) VISIBLE,
  INDEX `fk_Turno_Empleado1_idx` (`Empleado_idPersona` ASC) VISIBLE,
  INDEX `fk_Turno_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Turno_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `bd-turnos-grupo01`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `bd-turnos-grupo01`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Cliente1`
    FOREIGN KEY (`Cliente_idPersona`)
    REFERENCES `bd-turnos-grupo01`.`Cliente` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Empleado1`
    FOREIGN KEY (`Empleado_idPersona`)
    REFERENCES `bd-turnos-grupo01`.`Empleado` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `bd-turnos-grupo01`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

